### ISSUE TITLE
Add support for passing API key

### ISSUE THREAD

**Issue by kenorb** [bgr/omdb-cli#10]
```
$ omdbtool.py -t Cars
Traceback (most recent call last):
  File "omdbtool.py", line 80, in <module>
    apicall = urlopen('https://www.omdbapi.com/?%s' % urlencode(params))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 457, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 689, in http_error_401
    errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x1027f2440>)
```

**Comment by bgr** [comment]
Thanks for bringing this up, I see now that omdbapi.com has become [a paid service](https://www.patreon.com/posts/api-is-going-10743518).

I will be able to look into this in a week or so.

**Comment by bgr** [comment]
API key support added! Sorry it took longer than it should've.
